sudo: required
language: bash
services:
- docker
install: true
before_install:
- openssl aes-256-cbc -K $encrypted_0642de9fa44a_key -iv $encrypted_0642de9fa44a_iv -in .stuff.tar.gz.enc -out stuff.tar.gz -d
- file stuff.tar.gz
- tar xzvf stuff.tar.gz -C /tmp/
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/stuff/.deploy
- ssh-add /tmp/stuff/.deploy
- mv /tmp/stuff/.host ~/.ssh/config
- gem install travis
- sh /tmp/stuff/.travis_login
env:
- MOCK_CONFIG="mageia-cauldron-i586"
- MOCK_CONFIG="mageia-cauldron-x86_64"
script:
- export ARCH=$(echo ${MOCK_CONFIG} | cut -d- -f3)
- docker pull jmiahman/mageia-rpmbuilder-${ARCH}
- export DID=$(docker image ls | grep -m1 mageia-rpmbuilder-${ARCH} | awk '{print $3}')
- echo $DID
- docker run --privileged=true -e MOCK_CONFIG=${MOCK_CONFIG} -d -v "$(pwd):/rpmbuild" -v "/dev:/dev" $DID tail -f /dev/null
- export CID=$(docker ps -l | awk '{print $1}' | grep -v -m1 'CONTAINER')
- echo $CID
- docker exec $CID /bin/sh -c 'cd /rpmbuild && setarch '"${ARCH}"' rpmbuild -bs --undefine=_disable_source_fetch --define "_sourcedir /rpmbuild" --define "_topdir /rpmbuild" *.spec' --privileged=true
- src_rpm=$(find ./ -name *.src.rpm)
- echo ${src_rpm}
- ls ../;pwd
after_success:
- sudo -H pip install --upgrade pyOpenSSL ndg-httpsclient pyasn1 jinja2 requests[security] marshmallow copr-cli simplejson
- if [ "$TRAVIS_BRANCH" == "master" ] && [ -f $(find ./ -name *.src.rpm) ]; then copr-cli --config /tmp/stuff/.copr build jmiahman/Unity-Linux $(find ./ -name *.src.rpm); fi &
- scp -o StrictHostKeyChecking=no $(find ./ -name "*.rpm" -print|grep -v 'src.rpm') foobar2:rpm_staging/Unity-Linux/${ARCH}/
- scp -o StrictHostKeyChecking=no $(find ./ -name "*.rpm" -print|grep 'src.rpm') foobar2:rpm_staging/Unity-Linux/src/
- ssh -o StrictHostKeyChecking=no foobar2 "sh ~/bin/down_copr ${ARCH}"
